// <auto-generated />
using System;
using AccessWifi.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessWifi.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessWifi.Api.Features.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ap")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mac")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Nascimento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ssid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("AccessWifi.Api.Features.Settings.PortalSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AccessMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Banner")
                        .HasColumnType("text");

                    b.Property<string>("Favicon")
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Ssid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PortalSettings");
                });

            modelBuilder.Entity("AccessWifi.Api.Features.Settings.PortalSettings", b =>
                {
                    b.OwnsOne("AccessWifi.Api.Features.Settings.ThemeColors", "Colors", b1 =>
                        {
                            b1.Property<int>("PortalSettingsId")
                                .HasColumnType("integer");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("BrandDark")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Card")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Ink")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Muted")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.HasKey("PortalSettingsId");

                            b1.ToTable("PortalSettings");

                            b1.WithOwner()
                                .HasForeignKey("PortalSettingsId");
                        });

                    b.Navigation("Colors")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
