// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008175550_ConexoesDoPortal")]
    partial class ConexoesDoPortal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.DataBase.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RestrictToUnits")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.DataBase.AdminUserUnit", b =>
                {
                    b.Property<Guid>("IDUser")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDUnit")
                        .HasColumnType("uuid");

                    b.HasKey("IDUser", "IDUnit");

                    b.HasIndex("IDUnit");

                    b.ToTable("UserUnits", (string)null);
                });

            modelBuilder.Entity("Models.DataBase.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany");

                    b.HasIndex("Status", "NextRunAt");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Models.DataBase.CampaignDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IDRun")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDUnit")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("IDUnit");

                    b.HasIndex("IDRun", "IDUnit")
                        .IsUnique();

                    b.ToTable("CampaignDeliveries");
                });

            modelBuilder.Entity("Models.DataBase.CampaignEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IDCampaign")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDRun")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("IDCampaign", "CreatedAt");

                    b.ToTable("CampaignEvents");
                });

            modelBuilder.Entity("Models.DataBase.CampaignRecipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<Guid>("IDCustomer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDRun")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDUnit")
                        .HasColumnType("uuid");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("Milestone")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IDCustomer");

                    b.HasIndex("IDRun", "IDCustomer")
                        .IsUnique();

                    b.HasIndex("IDRun", "Status", "Id");

                    b.ToTable("CampaignRecipients");
                });

            modelBuilder.Entity("Models.DataBase.CampaignRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IDCampaign")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDCampaignVersion")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<int>("IgnoredCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<int>("SimulatedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Simulation")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IDCampaignVersion");

                    b.HasIndex("Status");

                    b.HasIndex("IDCampaign", "LocalDate")
                        .IsUnique();

                    b.HasIndex("IDCompany", "LocalDate");

                    b.ToTable("CampaignRuns");
                });

            modelBuilder.Entity("Models.DataBase.CampaignVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IDCampaign")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("IDCampaign", "Number")
                        .IsUnique();

                    b.ToTable("CampaignVersions");
                });

            modelBuilder.Entity("Models.DataBase.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ReportSendDay")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasDefaultValue("America/Belem");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Models.DataBase.CompanyCampaignKind", b =>
                {
                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("EnabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnabledBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("IDCompany", "Kind");

                    b.ToTable("CompanyCampaignKinds");
                });

            modelBuilder.Entity("Models.DataBase.Configuration", b =>
                {
                    b.Property<string>("IDConfiguration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IDConfiguration");

                    b.ToTable("Configuration", (string)null);
                });

            modelBuilder.Entity("Models.DataBase.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstVisitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FirstVisitDate")
                        .HasColumnType("date");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDLastUnit")
                        .HasColumnType("uuid");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastVisitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LastVisitDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany", "FirstVisitDate");

                    b.HasIndex("IDCompany", "LastVisitAt");

                    b.HasIndex("IDCompany", "Phone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Models.DataBase.CustomerUnit", b =>
                {
                    b.Property<Guid>("IDCustomer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDUnit")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstVisitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastVisitAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDCustomer", "IDUnit");

                    b.HasIndex("IDUnit");

                    b.ToTable("CustomerUnits");
                });

            modelBuilder.Entity("Models.DataBase.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ap")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IDUnit")
                        .HasColumnType("uuid");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mac")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Nascimento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ssid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IDUnit", "Mac")
                        .IsUnique();

                    b.HasIndex("IDUnit", "Timestamp");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("Models.DataBase.PortalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Banner")
                        .HasColumnType("text");

                    b.Property<string>("Favicon")
                        .HasColumnType("text");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Ssid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany")
                        .IsUnique();

                    b.ToTable("PortalSettings");
                });

            modelBuilder.Entity("Models.DataBase.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IDUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IDUser");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Models.DataBase.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DevicesSyncError")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("DevicesSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastReportSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PortalHost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany");

                    b.HasIndex("PortalHost")
                        .IsUnique()
                        .HasFilter("\"PortalHost\" <> ''");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Models.DataBase.UnitDevice", b =>
                {
                    b.Property<Guid>("IDUnit")
                        .HasColumnType("uuid");

                    b.Property<string>("Mac")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDUnit", "Mac");

                    b.HasIndex("Mac");

                    b.ToTable("UnitDevices");
                });

            modelBuilder.Entity("Models.DataBase.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ap")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IDCustomer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDUnit")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int>("LocalHour")
                        .HasColumnType("integer");

                    b.Property<bool>("NewInCompany")
                        .HasColumnType("boolean");

                    b.Property<bool>("NewInUnit")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IDCustomer");

                    b.HasIndex("IDUnit", "LocalDate");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Models.DataBase.AdminUser", b =>
                {
                    b.HasOne("Models.DataBase.Company", "Company")
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.DataBase.AdminUserUnit", b =>
                {
                    b.HasOne("Models.DataBase.Unit", null)
                        .WithMany()
                        .HasForeignKey("IDUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.DataBase.AdminUser", null)
                        .WithMany("Units")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.Campaign", b =>
                {
                    b.HasOne("Models.DataBase.Company", null)
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.CampaignDelivery", b =>
                {
                    b.HasOne("Models.DataBase.CampaignRun", null)
                        .WithMany()
                        .HasForeignKey("IDRun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.DataBase.Unit", null)
                        .WithMany()
                        .HasForeignKey("IDUnit")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.DataBase.CampaignEvent", b =>
                {
                    b.HasOne("Models.DataBase.Campaign", null)
                        .WithMany()
                        .HasForeignKey("IDCampaign")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.CampaignRecipient", b =>
                {
                    b.HasOne("Models.DataBase.Customer", null)
                        .WithMany()
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.DataBase.CampaignRun", null)
                        .WithMany()
                        .HasForeignKey("IDRun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.CampaignRun", b =>
                {
                    b.HasOne("Models.DataBase.Campaign", null)
                        .WithMany()
                        .HasForeignKey("IDCampaign")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.DataBase.CampaignVersion", null)
                        .WithMany()
                        .HasForeignKey("IDCampaignVersion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.CampaignVersion", b =>
                {
                    b.HasOne("Models.DataBase.Campaign", null)
                        .WithMany()
                        .HasForeignKey("IDCampaign")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.CompanyCampaignKind", b =>
                {
                    b.HasOne("Models.DataBase.Company", null)
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.Customer", b =>
                {
                    b.HasOne("Models.DataBase.Company", null)
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.CustomerUnit", b =>
                {
                    b.HasOne("Models.DataBase.Customer", null)
                        .WithMany()
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.DataBase.Unit", null)
                        .WithMany()
                        .HasForeignKey("IDUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.Lead", b =>
                {
                    b.HasOne("Models.DataBase.Unit", null)
                        .WithMany()
                        .HasForeignKey("IDUnit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.PortalSettings", b =>
                {
                    b.HasOne("Models.DataBase.Company", null)
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Models.DataBase.ThemeColors", "Colors", b1 =>
                        {
                            b1.Property<Guid>("PortalSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("BrandDark")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Card")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Ink")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Muted")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.HasKey("PortalSettingsId");

                            b1.ToTable("PortalSettings");

                            b1.WithOwner()
                                .HasForeignKey("PortalSettingsId");
                        });

                    b.Navigation("Colors")
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.RefreshToken", b =>
                {
                    b.HasOne("Models.DataBase.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.Unit", b =>
                {
                    b.HasOne("Models.DataBase.Company", null)
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Models.DataBase.CompanyUnifi", "Unifi", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApiKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("ConsoleId")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("Site")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<string>("SiteId")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<bool>("UnifiOs")
                                .HasColumnType("boolean");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<bool>("VerifySsl")
                                .HasColumnType("boolean");

                            b1.HasKey("UnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.Navigation("Unifi")
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.UnitDevice", b =>
                {
                    b.HasOne("Models.DataBase.Unit", null)
                        .WithMany()
                        .HasForeignKey("IDUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.Visit", b =>
                {
                    b.HasOne("Models.DataBase.Customer", null)
                        .WithMany()
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.DataBase.Unit", null)
                        .WithMany()
                        .HasForeignKey("IDUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.AdminUser", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
