// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723014915_AddLastReportSentAt")]
    partial class AddLastReportSentAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.DataBase.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.DataBase.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastReportSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ReportEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReportSendDay")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Models.DataBase.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ap")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mac")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Nascimento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ssid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany", "Timestamp");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("Models.DataBase.PortalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Banner")
                        .HasColumnType("text");

                    b.Property<string>("Favicon")
                        .HasColumnType("text");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uuid");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Ssid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IDCompany")
                        .IsUnique();

                    b.ToTable("PortalSettings");
                });

            modelBuilder.Entity("Models.DataBase.AdminUser", b =>
                {
                    b.HasOne("Models.DataBase.Company", "Company")
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.DataBase.Company", b =>
                {
                    b.OwnsOne("Models.DataBase.CompanyUnifi", "Unifi", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Site")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<bool>("UnifiOs")
                                .HasColumnType("boolean");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<bool>("VerifySsl")
                                .HasColumnType("boolean");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Unifi")
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.Lead", b =>
                {
                    b.HasOne("Models.DataBase.Company", null)
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DataBase.PortalSettings", b =>
                {
                    b.HasOne("Models.DataBase.Company", null)
                        .WithMany()
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Models.DataBase.ThemeColors", "Colors", b1 =>
                        {
                            b1.Property<Guid>("PortalSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("BrandDark")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Card")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Ink")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Muted")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.HasKey("PortalSettingsId");

                            b1.ToTable("PortalSettings");

                            b1.WithOwner()
                                .HasForeignKey("PortalSettingsId");
                        });

                    b.Navigation("Colors")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
